In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("ETFLIST.csv")

In [3]:

df = df.rename(columns={'Perc Hold(%)': 'Perc_Hold'})
df

,Scheme Name,Asset Type,Scheme Name.1,Company Name,Co_Name_Equity,Equity Rating,Rating,Sector,Fund Manager,Mkt Value,No Shares/Units,Perc_Hold,Price(BSE),Mkt cap,% of Equity Shares,YTM,YTC
0,360 ONE Gold ETF,Reverse Repo,360 ONE Gold ETF,CBLO,NaN,NaN,NaN,NaN,Rahul Khetawat,0.22,NaN,1.47,NaN,NaN,NaN,0.00,0
1,360 ONE Gold ETF,Gold,360 ONE Gold ETF,GOLD,NaN,NaN,NaN,NaN,Rahul Khetawat,14.35,15.0,95.89,NaN,NaN,NaN,0.00,0
2,360 ONE Silver ETF,Net CA & Others,360 ONE Silver ETF,Net CA & Others,NaN,NaN,NaN,NaN,Rahul Khetawat,0.64,NaN,5.53,NaN,NaN,NaN,0.00,0
3,360 ONE Silver ETF,Silver,360 ONE Silver ETF,Silver,NaN,NaN,NaN,NaN,Rahul Khetawat,8.56,810.0,97.11,NaN,NaN,NaN,0.00,0
4,AXIS BSE Sensex ETF,Equity,AXIS BSE Sensex ETF,Adani Ports & Special Economic Zone Ltd,Adani Ports,Average,NaN,Miscellaneous,Karthik Kumar,1.47,10148.0,1.08,"1,450.20","313,263.35",NaN,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11673,Zerodha Nifty Midcap 150 ETF,Equity,Zerodha Nifty Midcap 150 ETF,Waaree Energies Ltd,Waaree Energies,Good,NaN,Electric Equipment,Kedarnath Mirajkar,0.26,831.0,0.28,"3,138.70","90,169.58",NaN,0.00,0
11674,Zerodha Nifty Midcap 150 ETF,Equity,Zerodha Nifty Midcap 150 ETF,Yes Bank Ltd,Yes Bank,Bluechip,NaN,Banks - Private Sector,Kedarnath Mirajkar,0.98,482571.0,1.05,20.35,"63,823.04",NaN,0.00,0
11675,Zerodha Silver ETF,Reverse Repo,Zerodha Silver ETF,Clearing Corporation of India Ltd,NaN,NaN,NaN,Miscellaneous,Kedarnath Mirajkar,0.21,NaN,0.62,NaN,NaN,NaN,5.48,0
11676,Zerodha Silver ETF,Net CA & Others,Zerodha Silver ETF,Net CA & Others,NaN,NaN,NaN,NaN,Kedarnath Mirajkar,0.92,NaN,2.75,NaN,NaN,NaN,0.00,0
11677,Zerodha Silver ETF,Silver,Zerodha Silver ETF,Silver,NaN,NaN,NaN,NaN,Kedarnath Mirajkar,32.48,3072.0,96.63,0,0,0.0,0.00,0

In [ ]:
scheme_tags = {}

# Get unique scheme names
unique_schemes = df['Scheme Name'].unique()

for scheme in unique_schemes:
    # Filter for current scheme
    scheme_data = df[df['Scheme Name'] == scheme]
    # Create pivot table: index=Asset Type, columns=Scheme Name, values=sum of Perc Hold(%)
    pivot = scheme_data.pivot_table(index='Asset Type', values='Perc_Hold', aggfunc='sum')
    pivot = pivot.rename(columns={'Perc_Hold': scheme})
    pivot_reset = pivot.reset_index()  
    # Check for Gold asset type with Perc Hold > 90
    gold_row = pivot_reset[pivot_reset['Asset Type'] == 'Gold']
    GSec_row = pivot_reset[pivot_reset['Asset Type'] == 'Govt. Securities']
    Rrepo_row = pivot_reset[pivot_reset['Asset Type'] == 'Reverse Repo']
    ForeignEquity_row = pivot_reset[pivot_reset['Asset Type'] == 'Foreign Equity']
    Silver_row = pivot_reset[pivot_reset['Asset Type'] == 'Silver']
    equity_row = pivot_reset[pivot_reset['Asset Type'] == 'Equity']
    NCD_row = pivot_reset[pivot_reset['Asset Type'] == 'NCD']
    # If AUM less than 100 Cr than tag as poor 
    # Sum 'Mkt Value' column, ignoring NaN or blank values
    # mkt_value_sum = pd.to_numeric(scheme_data['Mkt Value'], errors='coerce').sum()
    # if mkt_value_sum < 100:
    #     scheme_tags[scheme] = ['Poor', 'AUM less than 100 Cr']
    if not gold_row.empty and gold_row[scheme].iloc[0] > 90:
        scheme_tags[scheme] = ['Good', '90percent gold']
    # Add more conditions here as needed
    elif not GSec_row.empty and GSec_row[scheme].iloc[0] > 90:
        scheme_tags[scheme] = ['Good', '90percent gsec']
    elif not Rrepo_row.empty and Rrepo_row[scheme].iloc[0] > 90:
        scheme_tags[scheme] = ['Good', '90percent rev_repo']
    elif not ForeignEquity_row.empty and ForeignEquity_row[scheme].iloc[0] > 90:
        scheme_tags[scheme] = ['Average', '90percent Foreign Equity']
    elif not Silver_row.empty and Silver_row[scheme].iloc[0] > 90:
        scheme_tags[scheme] = ['notag', '90percent Silver']
    elif not equity_row.empty and equity_row[scheme].iloc[0] > 90:
        pivot = scheme_data.pivot_table(index='Equity Rating', values='Perc_Hold', aggfunc='sum')
        pivot = pivot.rename(columns={'Perc_Hold': scheme})
        pivot_reset = pivot.reset_index()

        bluechip_row = pivot_reset[pivot_reset['Equity Rating'] == 'Bluechip']
        good_row = pivot_reset[pivot_reset['Equity Rating'] == 'Good']
        poor_row = pivot_reset[pivot_reset['Equity Rating'] == 'Poor']
        if not bluechip_row.empty and bluechip_row[scheme].iloc[0] > 70:
            scheme_tags[scheme] = ['Good', '70percent bluechip in equity']
        elif not good_row.empty and (bluechip_row[scheme].iloc[0] + good_row[scheme].iloc[0]) > 75:
            scheme_tags[scheme] = ['Good', '75percent bluechip and good in equity']
        elif not good_row.empty and good_row[scheme].iloc[0] > 75:
            scheme_tags[scheme] = ['Good', '75percent bluechip and good in equity']
        elif not poor_row.empty and poor_row[scheme].iloc[0] > 40:
            scheme_tags[scheme] = ['Poor', '40percent is poor in equity']
        else:
            scheme_tags[scheme] = ['Average', 'else average in equity']

    elif not NCD_row.empty and NCD_row[scheme].iloc[0] > 90:
        pivot = scheme_data.pivot_table(index='Rating', values='Perc_Hold', aggfunc='sum')
        pivot = pivot.rename(columns={'Perc_Hold': scheme})
        pivot_reset = pivot.reset_index()

        aaa_row = pivot_reset[pivot_reset['Rating'] in ['AAA','AAA (SO)', 'AAA (CE)', 'AAA (IND)', 'Reverse repo','Cash and CE', 'Fixed Deposits', 'T Bills', 'Sovereign', 'A1+']]
        aaplus_row = pivot_reset[pivot_reset['Rating'] in ['AA+','AA+ (SO)', 'AA+ (CE)']]
        aa_row = pivot_reset[pivot_reset['Rating'] in ['AA','AA (CE)']]
        if not aaa_row.empty and aaa_row[scheme].iloc[0] > 90:
            scheme_tags[scheme] = ['Good', '90percent AAA rated bond']
        elif not aaplus_row.empty and (aaa_row[scheme].iloc[0] + aaplus_row[scheme].iloc[0]) > 95:
            scheme_tags[scheme] = ['Good', '95percent AAA and AA+ bond']
        elif not aa_row.empty and (aaa_row[scheme].iloc[0] + aaplus_row[scheme].iloc[0] + aa_row[scheme].iloc[0]) > 85:
            scheme_tags[scheme] = ['Average', '85percent AAA,AAPlus and AA Bond']
        else:
            scheme_tags[scheme] = ['poor', 'rest average in bond']

    else:
        scheme_tags[scheme] = 'OtherTag'

scheme_tags

{'360 ONE Gold ETF': ['Good', '90percent gold'],
 '360 ONE Silver ETF': ['notag', '90percent Silver'],
 'AXIS BSE Sensex ETF': ['Good', '70percent bluechip in equity'],
 'AXIS Gold ETF': ['Good', '90percent gold'],
 'AXIS Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'AXIS Nifty AAA Bond Plus SDL Apr 2026 50:50 ETF': 'OtherTag',
 'AXIS Nifty Bank ETF': ['Good', '75percent bluechip and good in equity'],
 'AXIS Nifty Healthcare ETF': ['Good', '70percent bluechip in equity'],
 'AXIS Nifty IT ETF': ['Good', '70percent bluechip in equity'],
 'AXIS Nifty India Consumption ETF': ['Good', '70percent bluechip in equity'],
 'AXIS Nifty500 Value 50 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'AXIS Silver ETF': ['notag', '90percent Silver'],
 'Aditya Birla SL BSE Sensex ETF': ['Good', '70percent bluechip in equity'],
 'Aditya Birla SL CRISIL 10 Year Gilt ETF': ['Good', '90percent gsec'],
 'Aditya Birla SL CRISIL Broad Based Gilt ETF': ['Good', '90percent gsec'],
 'Aditya Birla SL CRISIL Liquid Overnight ETF': ['Good', '90percent rev_repo'],
 'Aditya Birla SL Gold ETF': ['Good', '90percent gold'],
 'Aditya Birla SL Nifty 200 Momentum 30 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Aditya Birla SL Nifty 200 Quality 30 ETF': ['Good',
  '70percent bluechip in equity'],
 'Aditya Birla SL Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'Aditya Birla SL Nifty Bank ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Aditya Birla SL Nifty Healthcare ETF': ['Good',
  '70percent bluechip in equity'],
 'Aditya Birla SL Nifty IT ETF': ['Good', '70percent bluechip in equity'],
 'Aditya Birla SL Nifty Next 50 ETF': ['Good', '70percent bluechip in equity'],
 'Aditya Birla SL Nifty PSE ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Aditya Birla SL Silver ETF': ['notag', '90percent Silver'],
 'Angel One Nifty 1D Rate Liquid ETF - Growth': ['Good', '90percent rev_repo'],
 'Angel One Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'Angel One Nifty Total Market ETF': ['Good',
  '75percent bluechip and good in equity'],
 'BHARAT Bond ETF - April 2030': 'OtherTag',
 'BHARAT Bond ETF - April 2031': 'OtherTag',
 'BHARAT Bond ETF - April 2032': 'OtherTag',
 'BHARAT Bond ETF - April 2033': 'OtherTag',
 'Bajaj Finserv Nifty 1D Rate Liquid ETF - Growth': ['Good',
  '90percent rev_repo'],
 'Bajaj Finserv Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'Bajaj Finserv Nifty Bank ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Bandhan Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'Baroda BNP Paribas Gold ETF': ['Good', '90percent gold'],
 'Baroda BNP Paribas NIFTY Bank ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Bharat 22 ETF': ['Good', '70percent bluechip in equity'],
 'CPSE ETF': ['Good', '70percent bluechip in equity'],
 'DSP BSE Liquid Rate ETF': ['Good', '90percent rev_repo'],
 'DSP BSE SENSEX Next 30 ETF': ['Good', '70percent bluechip in equity'],
 'DSP BSE Sensex ETF': ['Good', '70percent bluechip in equity'],
 'DSP Gold ETF': ['Good', '90percent gold'],
 'DSP NIFTY 1D Rate Liquid ETF': ['Good', '90percent rev_repo'],
 'DSP Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'DSP Nifty 50 Equal Weight ETF': ['Good', '70percent bluechip in equity'],
 'DSP Nifty Bank ETF': ['Good', '75percent bluechip and good in equity'],
 'DSP Nifty Healthcare ETF': ['Good', '70percent bluechip in equity'],
 'DSP Nifty IT ETF': ['Good', '70percent bluechip in equity'],
 'DSP Nifty Midcap 150 Quality 50 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'DSP Nifty PSU Bank ETF': ['Good', '70percent bluechip in equity'],
 'DSP Nifty Private Bank ETF': ['Good', '70percent bluechip in equity'],
 'DSP Nifty Top 10 Equal Weight ETF': ['Good', '70percent bluechip in equity'],
 'DSP Silver ETF': ['notag', '90percent Silver'],
 'Edelweiss BSE Capital Markets & Insurance ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Edelweiss Gold ETF': ['Good', '90percent gold'],
 'Edelweiss Nifty Bank ETF': ['Good', '75percent bluechip and good in equity'],
 'Edelweiss Nifty500 Multicap Momentum Quality 50 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Edelweiss Silver ETF': ['notag', '90percent Silver'],
 'Groww Gold ETF': ['Good', '90percent gold'],
 'Groww Nifty 1D Rate Liquid ETF': ['Good', '90percent rev_repo'],
 'Groww Nifty 200 ETF': ['Good', '70percent bluechip in equity'],
 'Groww Nifty 500 Low Volatility 50 ETF': ['Good',
  '70percent bluechip in equity'],
 'Groww Nifty 500 Momentum 50 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Groww Nifty EV & New Age Automotive ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Groww Nifty India Defence ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Groww Nifty India Railways PSU ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Groww Silver ETF': ['notag', '90percent Silver'],
 'HDFC BSE 500 ETF': ['Good', '75percent bluechip and good in equity'],
 'HDFC BSE SENSEX ETF': ['Good', '70percent bluechip in equity'],
 'HDFC Gold ETF': ['Good', '90percent gold'],
 'HDFC NIFTY 100 ETF': ['Good', '70percent bluechip in equity'],
 'HDFC NIFTY 1D Rate Liquid ETF - Growth': ['Good', '90percent rev_repo'],
 'HDFC NIFTY Bank ETF': ['Good', '75percent bluechip and good in equity'],
 'HDFC NIFTY Growth Sectors 15 ETF': ['Good', '70percent bluechip in equity'],
 'HDFC NIFTY IT ETF': ['Good', '70percent bluechip in equity'],
 'HDFC NIFTY Midcap 150 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'HDFC NIFTY NEXT 50 ETF': ['Good', '70percent bluechip in equity'],
 'HDFC NIFTY PSU BANK ETF': ['Good', '70percent bluechip in equity'],
 'HDFC NIFTY Private Bank ETF': ['Good', '70percent bluechip in equity'],
 'HDFC NIFTY Smallcap 250 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'HDFC NIFTY100 Low Volatility 30 ETF': ['Good',
  '70percent bluechip in equity'],
 'HDFC NIFTY100 Quality 30 ETF': ['Good', '70percent bluechip in equity'],
 'HDFC NIFTY200 Momentum 30 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'HDFC NIFTY50 Value 20 ETF': ['Good', '70percent bluechip in equity'],
 'HDFC Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'HDFC Silver ETF': ['notag', '90percent Silver'],
 'ICICI Pru BSE 500 ETF': ['Good', '75percent bluechip and good in equity'],
 'ICICI Pru BSE Liquid Rate ETF - Growth': ['Good', '90percent rev_repo'],
 'ICICI Pru BSE Liquid Rate ETF - IDCW': ['Good', '90percent rev_repo'],
 'ICICI Pru BSE Midcap Select ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru BSE Sensex ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Gold ETF': ['Good', '90percent gold'],
 'ICICI Pru Nifty 10 yr Benchmark G-Sec ETF': ['Good', '90percent gsec'],
 'ICICI Pru Nifty 100 ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Nifty 100 Low Volatility 30 ETF': ['Good',
  '70percent bluechip in equity'],
 'ICICI Pru Nifty 200 Momentum 30 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'ICICI Pru Nifty 200 Quality 30 ETF': ['Good',
  '70percent bluechip in equity'],
 'ICICI Pru Nifty 5 yr Benchmark G-Sec ETF': ['Good', '90percent gsec'],
 'ICICI Pru Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Nifty 50 Value 20 ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Nifty Alpha Low - Volatility 30 ETF': ['Good',
  '70percent bluechip in equity'],
 'ICICI Pru Nifty Auto ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Nifty Bank ETF': ['Good', '75percent bluechip and good in equity'],
 'ICICI Pru Nifty Commodities ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Nifty EV & New Age Automotive ETF': ['Good',
  '75percent bluechip and good in equity'],
 'ICICI Pru Nifty FMCG ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Nifty Financial Services Ex-Bank ETF': ['Good',
  '75percent bluechip and good in equity'],
 'ICICI Pru Nifty Healthcare ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Nifty IT ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Nifty India Consumption ETF': ['Good',
  '70percent bluechip in equity'],
 'ICICI Pru Nifty Infrastructure ETF': ['Good',
  '70percent bluechip in equity'],
 'ICICI Pru Nifty Metal ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Nifty Midcap 150 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'ICICI Pru Nifty Next 50 ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Nifty Oil & Gas ETF': ['Good',
  '75percent bluechip and good in equity'],
 'ICICI Pru Nifty PSU Bank ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Nifty Private Bank ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Nifty Top 15 Equal Weight ETF': ['Good',
  '70percent bluechip in equity'],
 'ICICI Pru Nifty200 Value 30 ETF': ['Good', '70percent bluechip in equity'],
 'ICICI Pru Silver ETF': ['notag', '90percent Silver'],
 'Invesco India Gold ETF': ['Good', '90percent gold'],
 'Invesco India Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'Kotak GOLD ETF': ['Good', '90percent gold'],
 'Kotak MSCI India ETF': ['Good', '70percent bluechip in equity'],
 'Kotak Nifty 100 Equal Weight ETF': ['Good', '70percent bluechip in equity'],
 'Kotak Nifty 100 Low Volatility 30 ETF': ['Good',
  '70percent bluechip in equity'],
 'Kotak Nifty 1D Rate Liquid ETF': ['Good', '90percent rev_repo'],
 'Kotak Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'Kotak Nifty 50 Value 20 ETF': ['Good', '70percent bluechip in equity'],
 'Kotak Nifty Alpha 50 ETF': ['Good', '75percent bluechip and good in equity'],
 'Kotak Nifty Bank ETF': ['Good', '75percent bluechip and good in equity'],
 'Kotak Nifty IT ETF': ['Good', '70percent bluechip in equity'],
 'Kotak Nifty India Consumption ETF': ['Good', '70percent bluechip in equity'],
 'Kotak Nifty MNC ETF': ['Good', '75percent bluechip and good in equity'],
 'Kotak Nifty Midcap 150 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Kotak Nifty Midcap 50 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Kotak Nifty PSU Bank ETF': ['Good', '70percent bluechip in equity'],
 'Kotak Silver ETF': ['notag', '90percent Silver'],
 'LIC MF BSE Sensex ETF': ['Good', '70percent bluechip in equity'],
 'LIC MF Gold ETF': ['Good', '90percent gold'],
 'LIC MF Nifty 100 ETF': ['Good', '70percent bluechip in equity'],
 'LIC MF Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'LIC MF Nifty 8-13 yr G-Sec ETF': ['Good', '90percent gsec'],
 'LIC MF Nifty Midcap 100 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Mirae Asset BSE 200 Equal Weight ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Mirae Asset BSE Select IPO ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Mirae Asset BSE Sensex ETF': ['Good', '70percent bluechip in equity'],
 'Mirae Asset Gold ETF': ['Good', '90percent gold'],
 'Mirae Asset Hang Seng TECH ETF': ['notag', '90percent Foreign Equity'],
 'Mirae Asset NYSE FANG+ ETF': ['notag', '90percent Foreign Equity'],
 'Mirae Asset Nifty 100 ESG Sector Leaders ETF': ['Good',
  '70percent bluechip in equity'],
 'Mirae Asset Nifty 100 Low Volatility 30 ETF': ['Good',
  '70percent bluechip in equity'],
 'Mirae Asset Nifty 1D Rate Liquid ETF - Growth': ['Good',
  '90percent rev_repo'],
 'Mirae Asset Nifty 1D Rate Liquid ETF-IDCW': ['Good', '90percent rev_repo'],
 'Mirae Asset Nifty 200 Alpha 30 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Mirae Asset Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'Mirae Asset Nifty 8-13 yr G-Sec ETF': ['Good', '90percent gsec'],
 'Mirae Asset Nifty Bank ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Mirae Asset Nifty EV and New Age Automotive ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Mirae Asset Nifty Financial Services ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Mirae Asset Nifty IT ETF': ['Good', '70percent bluechip in equity'],
 'Mirae Asset Nifty India Manufacturing ETF': ['Good',
  '70percent bluechip in equity'],
 'Mirae Asset Nifty India New Age Consumption ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Mirae Asset Nifty Metal ETF': ['Good', '70percent bluechip in equity'],
 'Mirae Asset Nifty MidSmallcap400 Momentum Quality 100 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Mirae Asset Nifty Midcap 150 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Mirae Asset Nifty Next 50 ETF': ['Good', '70percent bluechip in equity'],
 'Mirae Asset Nifty PSU Bank ETF': ['Good', '70percent bluechip in equity'],
 'Mirae Asset Nifty Smallcap 250 Momentum Quality 100 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Mirae Asset Nifty50 Equal Weight ETF': ['Good',
  '70percent bluechip in equity'],
 'Mirae Asset Nifty500 Multicap 50:25:25 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Mirae Asset S&P 500 Top 50 ETF': ['notag', '90percent Foreign Equity'],
 'Mirae Asset Silver ETF': ['notag', '90percent Silver'],
 'Motilal Oswal BSE Enhanced Value ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Motilal Oswal BSE Healthcare ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Motilal Oswal BSE India Infrastructure ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Motilal Oswal BSE Low Volatility ETF': ['Good',
  '70percent bluechip in equity'],
 'Motilal Oswal BSE Quality ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Motilal Oswal NASDAQ-100 ETF': ['notag', '90percent Foreign Equity'],
 'Motilal Oswal Nasdaq Q 50 ETF': ['notag', '90percent Foreign Equity'],
 'Motilal Oswal Nifty 200 Momentum 30 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Motilal Oswal Nifty 5 Year Benchmark G-Sec ETF': ['Good', '90percent gsec'],
 'Motilal Oswal Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'Motilal Oswal Nifty 50 Equal Weight ETF': ['Good',
  '70percent bluechip in equity'],
 'Motilal Oswal Nifty 500 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Motilal Oswal Nifty 500 Momentum 50 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Motilal Oswal Nifty Capital Market ETF': ['Average',
  'else average in equity'],
 'Motilal Oswal Nifty India Defence ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Motilal Oswal Nifty India Manufacturing ETF': ['Good',
  '70percent bluechip in equity'],
 'Motilal Oswal Nifty India Tourism ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Motilal Oswal Nifty Midcap 100 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Motilal Oswal Nifty Midcap150 Momentum 50 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Motilal Oswal Nifty Next 50 ETF': ['Good', '70percent bluechip in equity'],
 'Motilal Oswal Nifty PSE ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Motilal Oswal Nifty Realty ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Motilal Oswal Nifty Smallcap 250 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Nippon India BSE Sensex Next 30 ETF': ['Good',
  '70percent bluechip in equity'],
 'Nippon India ETF Gold BeES': ['Good', '90percent gold'],
 'Nippon India ETF Hang Seng BeES': ['notag', '90percent Foreign Equity'],
 'Nippon India ETF Nifty 100': ['Good', '70percent bluechip in equity'],
 'Nippon India ETF Nifty 1D Rate Liquid BeES': ['Good', '90percent rev_repo'],
 'Nippon India ETF Nifty 5 yr Benchmark G-Sec': ['Good', '90percent gsec'],
 'Nippon India ETF Nifty 50 BeES': ['Good', '70percent bluechip in equity'],
 'Nippon India ETF Nifty 50 Shariah BeES': ['Good',
  '70percent bluechip in equity'],
 'Nippon India ETF Nifty 50 Value 20': ['Good',
  '70percent bluechip in equity'],
 'Nippon India ETF Nifty 8-13 yr G-Sec Long Term Gilt': ['Good',
  '90percent gsec'],
 'Nippon India ETF Nifty Bank BeES': ['Good',
  '75percent bluechip and good in equity'],
 'Nippon India ETF Nifty Dividend Opportunities 50': ['Good',
  '70percent bluechip in equity'],
 'Nippon India ETF Nifty IT': ['Good', '70percent bluechip in equity'],
 'Nippon India ETF Nifty India Consumption': ['Good',
  '70percent bluechip in equity'],
 'Nippon India ETF Nifty Infrastructure BeES': ['Good',
  '70percent bluechip in equity'],
 'Nippon India ETF Nifty Midcap 150': ['Good',
  '75percent bluechip and good in equity'],
 'Nippon India ETF Nifty Next 50 Junior BeES': ['Good',
  '70percent bluechip in equity'],
 'Nippon India ETF Nifty PSU Bank BeES': ['Good',
  '70percent bluechip in equity'],
 'Nippon India ETF Nifty SDL Apr 2026 Top 20 Equal Weight': ['Good',
  '90percent gsec'],
 'Nippon India Nifty Auto ETF': ['Good', '70percent bluechip in equity'],
 'Nippon India Nifty Pharma ETF': ['Good', '70percent bluechip in equity'],
 'Nippon India Silver ETF': ['notag', '90percent Silver'],
 'Quantum Gold Fund (G)': ['Good', '90percent gold'],
 'Quantum Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'SBI BSE PSU Bank ETF': ['Good', '70percent bluechip in equity'],
 'SBI Gold ETF': ['Good', '90percent gold'],
 'SBI Nifty 10 yr Benchmark G-Sec ETF': ['Good', '90percent gsec'],
 'SBI Nifty 1D Rate Liquid ETF - IDCW': ['Good', '90percent rev_repo'],
 'SBI Nifty 200 Quality 30 ETF': ['Good', '70percent bluechip in equity'],
 'SBI Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'SBI Nifty Bank ETF': ['Good', '75percent bluechip and good in equity'],
 'SBI Nifty Consumption ETF': ['Good', '70percent bluechip in equity'],
 'SBI Nifty IT ETF': ['Good', '70percent bluechip in equity'],
 'SBI Nifty Next 50 ETF': ['Good', '70percent bluechip in equity'],
 'SBI Nifty Private Bank ETF': ['Good', '70percent bluechip in equity'],
 'SBI Nifty50 Equal Weight ETF': ['Good', '70percent bluechip in equity'],
 'SBI SILVER ETF': ['notag', '90percent Silver'],
 'Shriram Nifty 1D Rate Liquid ETF': ['Good', '90percent rev_repo'],
 'Tata Gold ETF': ['Good', '90percent gold'],
 'Tata Nifty 50 Exchange Traded Fund': ['Good',
  '70percent bluechip in equity'],
 'Tata Nifty India Digital Exchange Traded Fund': ['Good',
  '75percent bluechip and good in equity'],
 'Tata Nifty Private Bank ETF': ['Good', '70percent bluechip in equity'],
 'Tata Silver ETF': ['notag', '90percent Silver'],
 'UTI-BSE Sensex ETF': ['Good', '70percent bluechip in equity'],
 'UTI-BSE Sensex Next 50 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'UTI-Gold ETF': ['Good', '90percent gold'],
 'UTI-Nifty 10 yr Benchmark G-Sec ETF': ['Good', '90percent gsec'],
 'UTI-Nifty 5 yr Benchmark G-Sec ETF': ['Good', '90percent gsec'],
 'UTI-Nifty 50 ETF': ['Good', '70percent bluechip in equity'],
 'UTI-Nifty Bank Exchange Traded Fund': ['Good',
  '75percent bluechip and good in equity'],
 'UTI-Nifty IT ETF': ['Good', '70percent bluechip in equity'],
 'UTI-Nifty Midcap 150 ETF': ['Good', '75percent bluechip and good in equity'],
 'UTI-Nifty Next 50 ETF': ['Good', '70percent bluechip in equity'],
 'UTI-Silver Exchange Traded Fund': ['notag', '90percent Silver'],
 'Union Gold ETF': ['Good', '90percent gold'],
 'Zerodha Gold ETF': ['Good', '90percent gold'],
 'Zerodha Nifty 100 ETF': ['Good', '70percent bluechip in equity'],
 'Zerodha Nifty 1D Rate Liquid ETF': ['Good', '90percent rev_repo'],
 'Zerodha Nifty Midcap 150 ETF': ['Good',
  '75percent bluechip and good in equity'],
 'Zerodha Silver ETF': ['notag', '90percent Silver']}

In [5]:
list(scheme_tags.items())

[('360 ONE Gold ETF', ['Good', '90percent gold']),
 ('360 ONE Silver ETF', ['notag', '90percent Silver']),
 ('AXIS BSE Sensex ETF', ['Good', '70percent bluechip in equity']),
 ('AXIS Gold ETF', ['Good', '90percent gold']),
 ('AXIS Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('AXIS Nifty AAA Bond Plus SDL Apr 2026 50:50 ETF', 'OtherTag'),
 ('AXIS Nifty Bank ETF', ['Good', '75percent bluechip and good in equity']),
 ('AXIS Nifty Healthcare ETF', ['Good', '70percent bluechip in equity']),
 ('AXIS Nifty IT ETF', ['Good', '70percent bluechip in equity']),
 ('AXIS Nifty India Consumption ETF',
  ['Good', '70percent bluechip in equity']),
 ('AXIS Nifty500 Value 50 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('AXIS Silver ETF', ['notag', '90percent Silver']),
 ('Aditya Birla SL BSE Sensex ETF', ['Good', '70percent bluechip in equity']),
 ('Aditya Birla SL CRISIL 10 Year Gilt ETF', ['Good', '90percent gsec']),
 ('Aditya Birla SL CRISIL Broad Based Gilt ETF', ['Good', '90percent gsec']),
 ('Aditya Birla SL CRISIL Liquid Overnight ETF',
  ['Good', '90percent rev_repo']),
 ('Aditya Birla SL Gold ETF', ['Good', '90percent gold']),
 ('Aditya Birla SL Nifty 200 Momentum 30 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Aditya Birla SL Nifty 200 Quality 30 ETF',
  ['Good', '70percent bluechip in equity']),
 ('Aditya Birla SL Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('Aditya Birla SL Nifty Bank ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Aditya Birla SL Nifty Healthcare ETF',
  ['Good', '70percent bluechip in equity']),
 ('Aditya Birla SL Nifty IT ETF', ['Good', '70percent bluechip in equity']),
 ('Aditya Birla SL Nifty Next 50 ETF',
  ['Good', '70percent bluechip in equity']),
 ('Aditya Birla SL Nifty PSE ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Aditya Birla SL Silver ETF', ['notag', '90percent Silver']),
 ('Angel One Nifty 1D Rate Liquid ETF - Growth',
  ['Good', '90percent rev_repo']),
 ('Angel One Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('Angel One Nifty Total Market ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('BHARAT Bond ETF - April 2030', 'OtherTag'),
 ('BHARAT Bond ETF - April 2031', 'OtherTag'),
 ('BHARAT Bond ETF - April 2032', 'OtherTag'),
 ('BHARAT Bond ETF - April 2033', 'OtherTag'),
 ('Bajaj Finserv Nifty 1D Rate Liquid ETF - Growth',
  ['Good', '90percent rev_repo']),
 ('Bajaj Finserv Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('Bajaj Finserv Nifty Bank ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Bandhan Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('Baroda BNP Paribas Gold ETF', ['Good', '90percent gold']),
 ('Baroda BNP Paribas NIFTY Bank ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Bharat 22 ETF', ['Good', '70percent bluechip in equity']),
 ('CPSE ETF', ['Good', '70percent bluechip in equity']),
 ('DSP BSE Liquid Rate ETF', ['Good', '90percent rev_repo']),
 ('DSP BSE SENSEX Next 30 ETF', ['Good', '70percent bluechip in equity']),
 ('DSP BSE Sensex ETF', ['Good', '70percent bluechip in equity']),
 ('DSP Gold ETF', ['Good', '90percent gold']),
 ('DSP NIFTY 1D Rate Liquid ETF', ['Good', '90percent rev_repo']),
 ('DSP Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('DSP Nifty 50 Equal Weight ETF', ['Good', '70percent bluechip in equity']),
 ('DSP Nifty Bank ETF', ['Good', '75percent bluechip and good in equity']),
 ('DSP Nifty Healthcare ETF', ['Good', '70percent bluechip in equity']),
 ('DSP Nifty IT ETF', ['Good', '70percent bluechip in equity']),
 ('DSP Nifty Midcap 150 Quality 50 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('DSP Nifty PSU Bank ETF', ['Good', '70percent bluechip in equity']),
 ('DSP Nifty Private Bank ETF', ['Good', '70percent bluechip in equity']),
 ('DSP Nifty Top 10 Equal Weight ETF',
  ['Good', '70percent bluechip in equity']),
 ('DSP Silver ETF', ['notag', '90percent Silver']),
 ('Edelweiss BSE Capital Markets & Insurance ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Edelweiss Gold ETF', ['Good', '90percent gold']),
 ('Edelweiss Nifty Bank ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Edelweiss Nifty500 Multicap Momentum Quality 50 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Edelweiss Silver ETF', ['notag', '90percent Silver']),
 ('Groww Gold ETF', ['Good', '90percent gold']),
 ('Groww Nifty 1D Rate Liquid ETF', ['Good', '90percent rev_repo']),
 ('Groww Nifty 200 ETF', ['Good', '70percent bluechip in equity']),
 ('Groww Nifty 500 Low Volatility 50 ETF',
  ['Good', '70percent bluechip in equity']),
 ('Groww Nifty 500 Momentum 50 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Groww Nifty EV & New Age Automotive ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Groww Nifty India Defence ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Groww Nifty India Railways PSU ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Groww Silver ETF', ['notag', '90percent Silver']),
 ('HDFC BSE 500 ETF', ['Good', '75percent bluechip and good in equity']),
 ('HDFC BSE SENSEX ETF', ['Good', '70percent bluechip in equity']),
 ('HDFC Gold ETF', ['Good', '90percent gold']),
 ('HDFC NIFTY 100 ETF', ['Good', '70percent bluechip in equity']),
 ('HDFC NIFTY 1D Rate Liquid ETF - Growth', ['Good', '90percent rev_repo']),
 ('HDFC NIFTY Bank ETF', ['Good', '75percent bluechip and good in equity']),
 ('HDFC NIFTY Growth Sectors 15 ETF',
  ['Good', '70percent bluechip in equity']),
 ('HDFC NIFTY IT ETF', ['Good', '70percent bluechip in equity']),
 ('HDFC NIFTY Midcap 150 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('HDFC NIFTY NEXT 50 ETF', ['Good', '70percent bluechip in equity']),
 ('HDFC NIFTY PSU BANK ETF', ['Good', '70percent bluechip in equity']),
 ('HDFC NIFTY Private Bank ETF', ['Good', '70percent bluechip in equity']),
 ('HDFC NIFTY Smallcap 250 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('HDFC NIFTY100 Low Volatility 30 ETF',
  ['Good', '70percent bluechip in equity']),
 ('HDFC NIFTY100 Quality 30 ETF', ['Good', '70percent bluechip in equity']),
 ('HDFC NIFTY200 Momentum 30 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('HDFC NIFTY50 Value 20 ETF', ['Good', '70percent bluechip in equity']),
 ('HDFC Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('HDFC Silver ETF', ['notag', '90percent Silver']),
 ('ICICI Pru BSE 500 ETF', ['Good', '75percent bluechip and good in equity']),
 ('ICICI Pru BSE Liquid Rate ETF - Growth', ['Good', '90percent rev_repo']),
 ('ICICI Pru BSE Liquid Rate ETF - IDCW', ['Good', '90percent rev_repo']),
 ('ICICI Pru BSE Midcap Select ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru BSE Sensex ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Gold ETF', ['Good', '90percent gold']),
 ('ICICI Pru Nifty 10 yr Benchmark G-Sec ETF', ['Good', '90percent gsec']),
 ('ICICI Pru Nifty 100 ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty 100 Low Volatility 30 ETF',
  ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty 200 Momentum 30 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('ICICI Pru Nifty 200 Quality 30 ETF',
  ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty 5 yr Benchmark G-Sec ETF', ['Good', '90percent gsec']),
 ('ICICI Pru Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty 50 Value 20 ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty Alpha Low - Volatility 30 ETF',
  ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty Auto ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty Bank ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('ICICI Pru Nifty Commodities ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty EV & New Age Automotive ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('ICICI Pru Nifty FMCG ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty Financial Services Ex-Bank ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('ICICI Pru Nifty Healthcare ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty IT ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty India Consumption ETF',
  ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty Infrastructure ETF',
  ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty Metal ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty Midcap 150 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('ICICI Pru Nifty Next 50 ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty Oil & Gas ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('ICICI Pru Nifty PSU Bank ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty Private Bank ETF',
  ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty Top 15 Equal Weight ETF',
  ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Nifty200 Value 30 ETF', ['Good', '70percent bluechip in equity']),
 ('ICICI Pru Silver ETF', ['notag', '90percent Silver']),
 ('Invesco India Gold ETF', ['Good', '90percent gold']),
 ('Invesco India Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('Kotak GOLD ETF', ['Good', '90percent gold']),
 ('Kotak MSCI India ETF', ['Good', '70percent bluechip in equity']),
 ('Kotak Nifty 100 Equal Weight ETF',
  ['Good', '70percent bluechip in equity']),
 ('Kotak Nifty 100 Low Volatility 30 ETF',
  ['Good', '70percent bluechip in equity']),
 ('Kotak Nifty 1D Rate Liquid ETF', ['Good', '90percent rev_repo']),
 ('Kotak Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('Kotak Nifty 50 Value 20 ETF', ['Good', '70percent bluechip in equity']),
 ('Kotak Nifty Alpha 50 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Kotak Nifty Bank ETF', ['Good', '75percent bluechip and good in equity']),
 ('Kotak Nifty IT ETF', ['Good', '70percent bluechip in equity']),
 ('Kotak Nifty India Consumption ETF',
  ['Good', '70percent bluechip in equity']),
 ('Kotak Nifty MNC ETF', ['Good', '75percent bluechip and good in equity']),
 ('Kotak Nifty Midcap 150 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Kotak Nifty Midcap 50 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Kotak Nifty PSU Bank ETF', ['Good', '70percent bluechip in equity']),
 ('Kotak Silver ETF', ['notag', '90percent Silver']),
 ('LIC MF BSE Sensex ETF', ['Good', '70percent bluechip in equity']),
 ('LIC MF Gold ETF', ['Good', '90percent gold']),
 ('LIC MF Nifty 100 ETF', ['Good', '70percent bluechip in equity']),
 ('LIC MF Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('LIC MF Nifty 8-13 yr G-Sec ETF', ['Good', '90percent gsec']),
 ('LIC MF Nifty Midcap 100 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Mirae Asset BSE 200 Equal Weight ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Mirae Asset BSE Select IPO ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Mirae Asset BSE Sensex ETF', ['Good', '70percent bluechip in equity']),
 ('Mirae Asset Gold ETF', ['Good', '90percent gold']),
 ('Mirae Asset Hang Seng TECH ETF', ['notag', '90percent Foreign Equity']),
 ('Mirae Asset NYSE FANG+ ETF', ['notag', '90percent Foreign Equity']),
 ('Mirae Asset Nifty 100 ESG Sector Leaders ETF',
  ['Good', '70percent bluechip in equity']),
 ('Mirae Asset Nifty 100 Low Volatility 30 ETF',
  ['Good', '70percent bluechip in equity']),
 ('Mirae Asset Nifty 1D Rate Liquid ETF - Growth',
  ['Good', '90percent rev_repo']),
 ('Mirae Asset Nifty 1D Rate Liquid ETF-IDCW', ['Good', '90percent rev_repo']),
 ('Mirae Asset Nifty 200 Alpha 30 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Mirae Asset Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('Mirae Asset Nifty 8-13 yr G-Sec ETF', ['Good', '90percent gsec']),
 ('Mirae Asset Nifty Bank ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Mirae Asset Nifty EV and New Age Automotive ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Mirae Asset Nifty Financial Services ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Mirae Asset Nifty IT ETF', ['Good', '70percent bluechip in equity']),
 ('Mirae Asset Nifty India Manufacturing ETF',
  ['Good', '70percent bluechip in equity']),
 ('Mirae Asset Nifty India New Age Consumption ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Mirae Asset Nifty Metal ETF', ['Good', '70percent bluechip in equity']),
 ('Mirae Asset Nifty MidSmallcap400 Momentum Quality 100 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Mirae Asset Nifty Midcap 150 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Mirae Asset Nifty Next 50 ETF', ['Good', '70percent bluechip in equity']),
 ('Mirae Asset Nifty PSU Bank ETF', ['Good', '70percent bluechip in equity']),
 ('Mirae Asset Nifty Smallcap 250 Momentum Quality 100 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Mirae Asset Nifty50 Equal Weight ETF',
  ['Good', '70percent bluechip in equity']),
 ('Mirae Asset Nifty500 Multicap 50:25:25 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Mirae Asset S&P 500 Top 50 ETF', ['notag', '90percent Foreign Equity']),
 ('Mirae Asset Silver ETF', ['notag', '90percent Silver']),
 ('Motilal Oswal BSE Enhanced Value ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Motilal Oswal BSE Healthcare ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Motilal Oswal BSE India Infrastructure ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Motilal Oswal BSE Low Volatility ETF',
  ['Good', '70percent bluechip in equity']),
 ('Motilal Oswal BSE Quality ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Motilal Oswal NASDAQ-100 ETF', ['notag', '90percent Foreign Equity']),
 ('Motilal Oswal Nasdaq Q 50 ETF', ['notag', '90percent Foreign Equity']),
 ('Motilal Oswal Nifty 200 Momentum 30 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Motilal Oswal Nifty 5 Year Benchmark G-Sec ETF',
  ['Good', '90percent gsec']),
 ('Motilal Oswal Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('Motilal Oswal Nifty 50 Equal Weight ETF',
  ['Good', '70percent bluechip in equity']),
 ('Motilal Oswal Nifty 500 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Motilal Oswal Nifty 500 Momentum 50 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Motilal Oswal Nifty Capital Market ETF',
  ['Average', 'else average in equity']),
 ('Motilal Oswal Nifty India Defence ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Motilal Oswal Nifty India Manufacturing ETF',
  ['Good', '70percent bluechip in equity']),
 ('Motilal Oswal Nifty India Tourism ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Motilal Oswal Nifty Midcap 100 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Motilal Oswal Nifty Midcap150 Momentum 50 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Motilal Oswal Nifty Next 50 ETF', ['Good', '70percent bluechip in equity']),
 ('Motilal Oswal Nifty PSE ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Motilal Oswal Nifty Realty ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Motilal Oswal Nifty Smallcap 250 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('Nippon India BSE Sensex Next 30 ETF',
  ['Good', '70percent bluechip in equity']),
 ('Nippon India ETF Gold BeES', ['Good', '90percent gold']),
 ('Nippon India ETF Hang Seng BeES', ['notag', '90percent Foreign Equity']),
 ('Nippon India ETF Nifty 100', ['Good', '70percent bluechip in equity']),
 ('Nippon India ETF Nifty 1D Rate Liquid BeES',
  ['Good', '90percent rev_repo']),
 ('Nippon India ETF Nifty 5 yr Benchmark G-Sec', ['Good', '90percent gsec']),
 ('Nippon India ETF Nifty 50 BeES', ['Good', '70percent bluechip in equity']),
 ('Nippon India ETF Nifty 50 Shariah BeES',
  ['Good', '70percent bluechip in equity']),
 ('Nippon India ETF Nifty 50 Value 20',
  ['Good', '70percent bluechip in equity']),
 ('Nippon India ETF Nifty 8-13 yr G-Sec Long Term Gilt',
  ['Good', '90percent gsec']),
 ('Nippon India ETF Nifty Bank BeES',
  ['Good', '75percent bluechip and good in equity']),
 ('Nippon India ETF Nifty Dividend Opportunities 50',
  ['Good', '70percent bluechip in equity']),
 ('Nippon India ETF Nifty IT', ['Good', '70percent bluechip in equity']),
 ('Nippon India ETF Nifty India Consumption',
  ['Good', '70percent bluechip in equity']),
 ('Nippon India ETF Nifty Infrastructure BeES',
  ['Good', '70percent bluechip in equity']),
 ('Nippon India ETF Nifty Midcap 150',
  ['Good', '75percent bluechip and good in equity']),
 ('Nippon India ETF Nifty Next 50 Junior BeES',
  ['Good', '70percent bluechip in equity']),
 ('Nippon India ETF Nifty PSU Bank BeES',
  ['Good', '70percent bluechip in equity']),
 ('Nippon India ETF Nifty SDL Apr 2026 Top 20 Equal Weight',
  ['Good', '90percent gsec']),
 ('Nippon India Nifty Auto ETF', ['Good', '70percent bluechip in equity']),
 ('Nippon India Nifty Pharma ETF', ['Good', '70percent bluechip in equity']),
 ('Nippon India Silver ETF', ['notag', '90percent Silver']),
 ('Quantum Gold Fund (G)', ['Good', '90percent gold']),
 ('Quantum Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('SBI BSE PSU Bank ETF', ['Good', '70percent bluechip in equity']),
 ('SBI Gold ETF', ['Good', '90percent gold']),
 ('SBI Nifty 10 yr Benchmark G-Sec ETF', ['Good', '90percent gsec']),
 ('SBI Nifty 1D Rate Liquid ETF - IDCW', ['Good', '90percent rev_repo']),
 ('SBI Nifty 200 Quality 30 ETF', ['Good', '70percent bluechip in equity']),
 ('SBI Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('SBI Nifty Bank ETF', ['Good', '75percent bluechip and good in equity']),
 ('SBI Nifty Consumption ETF', ['Good', '70percent bluechip in equity']),
 ('SBI Nifty IT ETF', ['Good', '70percent bluechip in equity']),
 ('SBI Nifty Next 50 ETF', ['Good', '70percent bluechip in equity']),
 ('SBI Nifty Private Bank ETF', ['Good', '70percent bluechip in equity']),
 ('SBI Nifty50 Equal Weight ETF', ['Good', '70percent bluechip in equity']),
 ('SBI SILVER ETF', ['notag', '90percent Silver']),
 ('Shriram Nifty 1D Rate Liquid ETF', ['Good', '90percent rev_repo']),
 ('Tata Gold ETF', ['Good', '90percent gold']),
 ('Tata Nifty 50 Exchange Traded Fund',
  ['Good', '70percent bluechip in equity']),
 ('Tata Nifty India Digital Exchange Traded Fund',
  ['Good', '75percent bluechip and good in equity']),
 ('Tata Nifty Private Bank ETF', ['Good', '70percent bluechip in equity']),
 ('Tata Silver ETF', ['notag', '90percent Silver']),
 ('UTI-BSE Sensex ETF', ['Good', '70percent bluechip in equity']),
 ('UTI-BSE Sensex Next 50 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('UTI-Gold ETF', ['Good', '90percent gold']),
 ('UTI-Nifty 10 yr Benchmark G-Sec ETF', ['Good', '90percent gsec']),
 ('UTI-Nifty 5 yr Benchmark G-Sec ETF', ['Good', '90percent gsec']),
 ('UTI-Nifty 50 ETF', ['Good', '70percent bluechip in equity']),
 ('UTI-Nifty Bank Exchange Traded Fund',
  ['Good', '75percent bluechip and good in equity']),
 ('UTI-Nifty IT ETF', ['Good', '70percent bluechip in equity']),
 ('UTI-Nifty Midcap 150 ETF',
  ['Good', '75percent bluechip and good in equity']),
 ('UTI-Nifty Next 50 ETF', ['Good', '70percent bluechip in equity']),
 ('UTI-Silver Exchange Traded Fund', ['notag', '90percent Silver']),
 ('Union Gold ETF', ['Good', '90percent gold']),
 ('Zerodha Gold ETF', ['Good', '90percent gold']),
 ('Zerodha Nifty 100 ETF', ['Good', '70percent bluechip in equity']),
 ('Zerodha Nifty 1D Rate Liquid ETF', ['Good', '90percent rev_repo']),
 ('Zerodha Nifty Midcap 150 ETF',
  ['Good', '75percent bluechip and good in equity']),

In [6]:
scheme_tags_df = pd.DataFrame(list(scheme_tags.items()), columns=['Scheme Name', 'Tag'])
scheme_tags_df

,Scheme Name,Tag
0,360 ONE Gold ETF,"[Good, 90percent gold]"
1,360 ONE Silver ETF,"[notag, 90percent Silver]"
2,AXIS BSE Sensex ETF,"[Good, 70percent bluechip in equity]"
3,AXIS Gold ETF,"[Good, 90percent gold]"
4,AXIS Nifty 50 ETF,"[Good, 70percent bluechip in equity]"
...,...,...
254,Zerodha Gold ETF,"[Good, 90percent gold]"
255,Zerodha Nifty 100 ETF,"[Good, 70percent bluechip in equity]"
256,Zerodha Nifty 1D Rate Liquid ETF,"[Good, 90percent rev_repo]"
257,Zerodha Nifty Midcap 150 ETF,"[Good, 75percent bluechip and good in equity]"
258,Zerodha Silver ETF,"[notag, 90percent Silver]"

In [7]:
scheme_tags_df.to_csv("scheme_tag.csv")

In [8]:
scheme_tags_df

,Scheme Name,Tag
0,360 ONE Gold ETF,"[Good, 90percent gold]"
1,360 ONE Silver ETF,"[notag, 90percent Silver]"
2,AXIS BSE Sensex ETF,"[Good, 70percent bluechip in equity]"
3,AXIS Gold ETF,"[Good, 90percent gold]"
4,AXIS Nifty 50 ETF,"[Good, 70percent bluechip in equity]"
...,...,...
254,Zerodha Gold ETF,"[Good, 90percent gold]"
255,Zerodha Nifty 100 ETF,"[Good, 70percent bluechip in equity]"
256,Zerodha Nifty 1D Rate Liquid ETF,"[Good, 90percent rev_repo]"
257,Zerodha Nifty Midcap 150 ETF,"[Good, 75percent bluechip and good in equity]"
258,Zerodha Silver ETF,"[notag, 90percent Silver]"